FROM golang:1.17.5

RUN apt-get update

RUN apt-get install autoconf automake libtool curl make g++ unzip -y
RUN git clone https://github.com/google/protobuf.git

RUN cd ./protobuf && bash ./autogen.sh && ./configure && make && make install && ldconfig