From golang:1.14.3-alpine

MAINTAINER Simon "simon.shi@treelab.co"

RUN sed -i 's/dl-cdn.alpinelinux.org/mirrors.tuna.tsinghua.edu.cn/g' /etc/apk/repositories \
  && apk update --no-cache \
  && export PKGS="git docker openssh-client make gcc g++ python linux-headers paxctl libgcc libstdc++ bash curl" \
  && apk add --no-cache $PKGS \
  && apk add --no-cache libc6-compat