FROM python:3.9.5-slim

ENV LANG en_US.UTF-8
ENV TZ=Asia/Shanghai
ENV LANGUAGE en_US.UTF-8
ENV LC_ALL en_US.UTF-8

RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone
RUN sed -i "s@http://deb.debian.org@http://mirrors.aliyun.com@g" /etc/apt/sources.list &&  rm -Rf /var/lib/apt/lists/*
RUN apt-get update && apt-get install -y iputils-ping git postgresql postgresql-contrib wget
RUN apt-get install -y default-mysql-client
RUN pip3 install colorlog==6.4.1
RUN pip3 install ruamel.yaml==0.17.4
RUN pip3 install cassandra-driver==3.25.0
