FROM alpine:latest AS helmDown
RUN apk add --no-cache curl tar
RUN curl -LO https://get.helm.sh/helm-v3.9.3-linux-amd64.tar.gz && \
    tar -zxvf helm-v3.7.0-linux-amd64.tar.gz 

FROM registry.cn-zhangjiakou.aliyuncs.com/caminer/python:3.9.5-devops
EXPOSE 8000
ENV LANG en_US.UTF-8
ENV TZ=Asia/Shanghai
COPY --from=helmDown /linux-amd64/helm /usr/local/bin && chmod 777 /usr/local/bin/helm
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone
RUN sed -i "s@http://deb.debian.org@http://mirrors.aliyun.com@g" /etc/apt/sources.list &&  rm -Rf /var/lib/apt/lists/*
RUN apt-get update && apt-get install -y postgresql postgresql-contrib