FROM python:3.9.5-slim

ENV LANG en_US.UTF-8
ENV TZ=Asia/Shanghai
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone
RUN sed -i "s@http://deb.debian.org@http://mirrors.aliyun.com@g" /etc/apt/sources.list &&  rm -Rf /var/lib/apt/lists/*
RUN apt-get update && apt-get install -y iputils-ping git postgresql postgresql-contrib wget
RUN wget https://dev.mysql.com/get/mysql-apt-config_0.8.22-1_all.deb
RUN apt-get install -y ./mysql-apt-config_0.8.22-1_all.deb
RUN apt install -y mysql-client